
# Tool Panel
tool.spawnpoint.name=Editor de punto de spawn
tool.spawnpoint.desc=Añadir, remover o cambiar puntos de Spawn en el mapa.
tool.spawnpoint.0=Estas moviendo un punto de spawn
tool.spawnpoint.left=Crear punto de spawn
tool.spawnpoint.left_1=Aplicar configuracion al punto de spawn
tool.spawnpoint.left_2=Colocar punto de spawn seleccionado
tool.spawnpoint.right=Remover punto de spawn
tool.spawnpoint.reload=Rotar un punto de spawn
tool.spawnpoint.use=Seleccionar y mover punto de spawn
tool.spawnpoint.master=Punto de spawn maestro
tool.spawnpoint.master_desc=Los puntos de spawn maestros son elegidos sobre los puntos de spawn normal por el selector predeterminado
tool.spawnpoint.rotation=Rotacion
tool.spawnpoint.rotate_degrees=Grados de rotacion 
tool.spawnpoint.commands=Comandos
tool.spawnpoint.button_reset_map_created=Restaurar puntos de spawn predeterminados
tool.spawnpoint.button_restore=Restaurar puntos de spawn predeterminados faltantes
tool.spawnpoint.button_remove_map=Remover puntos de spawn predeterminados
tool.spawnpoint.button_remove_player=Remover puntos de spawn creados por el jugador

# Notifications
hint.spawnpoint.removed_map_created=Removido todos los puntos de spawn predeterminados!
hint.spawnpoint.removed_player_created=Removido todos los puntos de spawn creados por el jugador!
hint.spawnpoint.restore=Restaurado puntos de spawn predeterminados!
hint.spawnpoint.reset_map_created=Los puntos de spawn predeterminados han sido reseteados!

# UI/UX
spawnpoint.master=Maestro