tool.spawnpoint.name=Editor de punto de spawn
tool.spawnpoint.desc=Añadir, remover o cambiar puntos de Spawn en el mapa.
tool.spawnpoint.left=Crear punto de spawn
tool.spawnpoint.left_1=Aplicar configuracion al punto de spawn
tool.spawnpoint.right=Remover punto de spawn
tool.spawnpoint.reload=Rotar un punto de spawn
tool.spawnpoint.master=Punto de spawn maestro
tool.spawnpoint.rotation=Rotacion del punto de spawn
tool.spawnpoint.rotate_degrees=Grados de rotacion 
tool.spawnpoint.button_restore=Restaurar puntos de spawn predeterminados del mapa
tool.spawnpoint.button_destroy_map=Destruir puntos de spawn creados por el mapa
tool.spawnpoint.button_destroy_player=Destruir puntos de spawn creados por el jugador
spawnpoint.master=Maestro
info_player_start=Punto de spawn del jugador