tool.spawnpoint.name=Редактор точек спавна
tool.spawnpoint.desc=Добавить, удалить или изменить точки спавна на карте
tool.spawnpoint.0=Вы передвигаете точку спавна
tool.spawnpoint.left=Создать точку спавна
tool.spawnpoint.left_1=Применить настройки к точке спавна
tool.spawnpoint.left_2=Поставить выбранную точку спавна
tool.spawnpoint.right=Удалить точку спавна
tool.spawnpoint.reload=Повернуть точку спавна
tool.spawnpoint.use=Выделить и передвинуть точку спавна
tool.spawnpoint.master=Основная точка спавна
tool.spawnpoint.master_desc=По умолчанию, игра выбирает и использует Главные/Основные точки спавна поверх обычных точек спавна
tool.spawnpoint.rotation=Поворот точки спавна
tool.spawnpoint.rotate_degrees=Угол поворота
tool.spawnpoint.button_restore=Восстановить стандартные точки спавна карты
tool.spawnpoint.button_remove_map=Удалить точки спавна, созданные картой
tool.spawnpoint.button_remove_player=Удалить точки спавна, созданные игроком
spawnpoint.master=Основная
info_player_start=Точка спавна Игрока