tool.spawnpoint.name=Spawnpoint Editor
tool.spawnpoint.desc=Add, remove, or change spawnpoints on the map.
tool.spawnpoint.0=You are moving a Spawnpoint.
tool.spawnpoint.left=Create Spawnpoint
tool.spawnpoint.left_1=Apply settings to Spawnpoint
tool.spawnpoint.left_2=Place selected Spawnpoint
tool.spawnpoint.right=Remove Spawnpoint
tool.spawnpoint.reload=Rotate Spawnpoint
tool.spawnpoint.use=Select and move Spawnpoint
tool.spawnpoint.master=Master Spawnpoint
tool.spawnpoint.master_desc=Master Spawnpoints are chosen above normal spawnpoints by the default selector.
tool.spawnpoint.rotation=Spawnpoint Rotation
tool.spawnpoint.rotate_degrees=Rotate Degrees
tool.spawnpoint.button_restore=Restore Default Map Spawnpoints
tool.spawnpoint.button_remove_map=Remove Map Created Spawnpoints
tool.spawnpoint.button_remove_player=Remove Player Created Spawnpoints
spawnpoint.master=Master
info_player_start=Player Spawn Point
