
# Tool Panel
tool.spawnpoint.name=Editor de pontos de spawn
tool.spawnpoint.desc=Adicionar, remover ou mudar pontos de spawn no mapa
tool.spawnpoint.0=Você está movendo um ponto de spawn
tool.spawnpoint.left=Criar ponto de spawn
tool.spawnpoint.left_1=Aplicar configurações para o ponto de spawn
tool.spawnpoint.left_2=Colocar ponto de spawn selecionado
tool.spawnpoint.right=Remover ponto de spawn
tool.spawnpoint.reload=Rotacionar ponto de spawn
tool.spawnpoint.use=Selecionar e mover ponto de spawn
tool.spawnpoint.master=Ponto de spawn mestre 
tool.spawnpoint.master_desc=Pontos de spawn mestre são selecionados antes de outros spawn pelo seletor padrão!
tool.spawnpoint.rotation=Rotação
tool.spawnpoint.rotate_degrees=Ângulos de rotação
tool.spawnpoint.commands=Comandos
tool.spawnpoint.button_reset_map_created=Resetar pontos de spawn
tool.spawnpoint.button_restore=Restaurar pontos de spawn faltantes
tool.spawnpoint.button_remove_map=Remover pontos de spawn padrões
tool.spawnpoint.button_remove_player=Remover pontos de spawn criados por players

# Notifications
hint.spawnpoint.removed_map_created=Todos pontos de spawn foram removidos!
hint.spawnpoint.removed_player_created=Removido todos os pontos de spawn criados por players!
hint.spawnpoint.restore=Pontos de spawn originais restaurados!
hint.spawnpoint.reset_map_created=Pontos de spawn originais do mapa foram restaurados!

# UI/UX
spawnpoint.master=Mestre